version: "3.7"
services:
  minisched-server:
    image: minisched
    container_name: minisched
    environment:
      - PORT=1212
      - KUBE_SCHEDULER_SIMULATOR_ETCD_URL=http://minisched-etcd:2379
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "1212:1212"
    restart: always
    tty: true
    networks:
      - minisched-internal-network
  minisched-etcd:
    image: quay.io/coreos/etcd:v3.4.0
    container_name: minisched-etcd
    restart: always
    volumes:
      - minisched-etcd-data:/var/lib/etcd
    command: etcd --advertise-client-urls http://minisched-etcd:2379 --data-dir /var/lib/etcd --listen-client-urls http://0.0.0.0:2379 --initial-cluster-state new --initial-cluster-token tkn
    networks:
      - minisched-internal-network
volumes:
  minisched-etcd-data:
networks:
  minisched-internal-network:
    driver: bridge

